language: generic
dist: trusty
sudo: false


env:
  global:
    - PATH="/opt/chefdk/bin:/opt/chef/bin:/opt/chef/embedded/bin:/opt/chefdk/embedded/bin:$PATH"
  matrix:
    - COOKBOOK_PATH="cookbooks"

install:
  - sudo apt-get update -q
  - sudo apt-get install -q virtualbox --fix-missing
  - sudo wget -nv https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.2_x86_64.deb
  - sudo dpkg -i vagrant_1.7.2_x86_64.deb
  - bundle install

addons:
  apt:
   sources:
   - chef-stable-trusty
   packages:
   - chefdk


script: kitchen verify
